name: clot
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  hive: ^2.2.3
  flutter_svg: ^2.0.17
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
